#!/usr/bin/env python
#coding=utf-8

import numpy as np
import cv2

img=cv2.imread("lenna.png",0)

#转换为16位有符号的数据类型

#求x方向的一阶导数
x=cv2.Sobel(img,cv2.CV_16S,1,0)
#求y方向的一阶导数
y=cv2.Sobel(img,cv2.CV_16S,0,1)


#转回原来的uint8形式 convertScaleAbs()
absX=cv2.convertScaleAbs(x)
absY=cv2.convertScaleAbs(y)


#用cv2.addWeighted()函数组合
dst=cv2.addWeighted(absX,0.5,absY,0.5,0)

cv2.imshow("absX",absX)
cv2.imshow("absY",absY)

cv2.imshow("result",dst)

cv2.waitKey(0)

cv2.destroyAllWindows()
